return function (context) return {
"local main = function (static_data)\n  local create\n  local append\n  local append_unpack\n  local S\n  local SS\n  local action_data = (function ()\n    ";
context["custom_data"];
"\n    return { ";
context["action_data"];
" }\n  end)()\n  local error = error\n  local select = select\n  local table_unpack = table.unpack or unpack\n  local symbol_names = static_data.symbol_names\n  local actions = static_data.actions\n  local max_state = #actions\n  local heads = static_data.heads\n  local sizes = static_data.sizes\n  local semantic_actions = static_data.semantic_actions\n  local stack = { 1 }\n  local nodes = {}\n  function create(symbol)\n    return { [0] = symbol }\n  end\n  function append(...)\n    for i = 1, select(\"#\", ...) do\n      SS[#SS + 1] = select(i, ...)\n    end\n  end\n  function append_unpack(...)\n    for i = 1, select(\"#\", ...) do\n      append(table_unpack((select(i, ...))))\n    end\n  end\n  return function (token)\n    local symbol = token[0]\n    if symbol then\n      while true do\n        local state = stack[#stack]\n        local action = actions[state][symbol]\n        if action == 0 then\n          if token.f and token.n and token.c and token.s then\n            error(token.f..\":\"..token.n..\":\"..token.c..\": parser error (cannot transition near '\"..token.s..\"')\")\n          else\n            error(\"parser error (cannot transition near '\"..symbol_names[symbol]..\"')\")\n          end\n        end\n        if action <= max_state then\n          stack[#stack + 1] = action\n          nodes[#nodes + 1] = token\n          break\n        end\n        local index = action - max_state\n        if index == 1 then\n          local node = nodes[#nodes]\n          stack[#stack] = nil\n          nodes[#nodes] = nil\n          return node\n        end\n        local head = heads[index]\n        local size = sizes[index]\n        S = { [0] = { [0] = head } }\n        SS = { [0] = head }\n        local sf, si, sj, sn, sc\n        local n = #nodes - size\n        for i = 1, size do\n          local s = nodes[n + i]\n          S[i] = s\n          SS[i] = s\n          if not sf then\n            sf, si, sj, sn, sc = s.f, s.i, s.j, s.n, s.c\n          elseif sf == s.f then\n            if not si or si > s.i then\n              si = s.i\n            end\n            if not sj or sj < s.j then\n              sj = s.j\n            end\n            if not sn or sn > s.n or (sn == s.n and (not sc or sc > s.c)) then\n              sn, sc = s.n, s.c\n            end\n          end\n        end\n        for i = 1, size do\n          stack[#stack] = nil\n          nodes[#nodes] = nil\n        end\n        action_data[semantic_actions[index]]()\n        SS.f, SS.i, SS.j, SS.n, SS.c = sf, si, sj, sn, sc\n        local state = stack[#stack]\n        stack[#stack + 1] = actions[state][head]\n        nodes[#nodes + 1] = SS\n      end\n    end\n  end\nend\nlocal static_data = { ";
context["static_data"];
" }\nreturn setmetatable({}, {\n  __index = static_data;\n  __call = function (static_data)\n    return main(static_data)\n  end;\n})\n";
} end
